version: '2'
services:
  # maven:
  #   build: ./maven
  #   env_file: .env
  #   command: mvn -T 2C -f src clean install sakai:deploy
  #   volumes:
  #     - ./maven/src:/usr/src/mymaven/src
  #     - ./maven/target:/usr/src/mymaven/target
  #     - ./maven/.m2:/root/.m2
  #   networks:
  #     sakai.local:
  #       aliases:
  #         - maven.sakai.local
        # ipv4_address: ${MAVEN_IP}
  tomcat:
    build: ./tomcat
    ports:
      - ${TOMCAT_PORT}:8080
    env_file: .env
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./maven/target/webapps:/usr/local/tomcat/webapps
      - ./maven/target/components:/usr/local/tomcat/components
      - ./maven/target/endorsed:/usr/local/tomcat/endorsed
      - ./maven/target/sakai:/usr/local/tomcat/sakai
      - ./maven/target/lib:/usr/local/tomcat/sakai/lib
    command: ["/usr/local/bin/wait-for-it.sh", "${MYSQL_HOST}:${MYSQL_PORT}", "--", "/usr/local/bin/appstart.sh"]
    depends_on:
      - db
      # - maven
    networks:
      sakai.local:
        aliases:
          - tomcat.sakai.local
        ipv4_address: ${TOMCAT_IP}
  db:
    build: ./db
    ports:
      - ${MYSQL_PORT}:3306
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/config.sh:/docker-entrypoint-initdb.d/config.sh
    networks:
      sakai.local:
        aliases:
          - db.sakai.local
        ipv4_address: ${DB_IP}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_HOST=${MYSQL_HOST}
    networks:
      sakai.local:
        aliases:
          - pma.sakai.local
networks:
  sakai.local:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
        gateway: 172.16.239.1
