version: '2'
services:
  maven:
    build: ./maven
    env_file: .env
    command: mvn -T 2C -f src clean install sakai:deploy
    volumes:
      - ./sakai/src:/usr/src/mymaven/src
      - ./sakai/target:/usr/src/mymaven/target
      - ./sakai/.m2:/root/.m2
    networks:
      sakainet:
        aliases:
          - maven
        # ipv4_address: ${MAVEN_IP}
  tomcat:
    build: ./tomcat
    ports:
      - ${TOMCAT_PORT}:8080
    env_file: .env
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./sakai/target/webapps:/usr/local/tomcat/webapps
      - ./sakai/target/components:/usr/local/tomcat/components
      - ./sakai/target/endorsed:/usr/local/tomcat/endorsed
      - ./sakai/target/sakai:/usr/local/tomcat/sakai
      - ./sakai/target/lib:/usr/local/tomcat/lib
    depends_on:
      - db
      - maven
    networks:
      sakainet:
        aliases:
          - tomcat
        # ipv4_address: ${TOMCAT_IP}
  db:
    build: ./db
    ports:
      - 3636:3306
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/config.sh:/docker-entrypoint-initdb.d/config.sh
    networks:
      sakainet:
        aliases:
          - db
        # ipv4_address: ${DB_IP}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_HOST=${MYSQL_HOST}
    networks:
      - sakainet
networks:
  sakainet:
    driver: bridge
    ipam:
      driver: default
      # config:
      # - subnet: 172.16.239.0/24
        # gateway: 172.16.239.1
